### PR TITLE
ernest-cli docs will open ernest.io docs section

### PR DESCRIPTION
**Pull request by rawgni**
closes ernestio/ernest#156

### CODE REVIEW

**Comment by adriacidre** [comment]
@rawgni even your go code is importing https://github.com/skratchdot/open-golang/ the library is not found on the  system:
```
docs.go:10:2: cannot find package "github.com/skratchdot/open-golang/open" in any of:
	/usr/local/go/src/github.com/skratchdot/open-golang/open (from $GOROOT)
	/home/ubuntu/.go_workspace/src/github.com/skratchdot/open-golang/open (from $GOPATH)
	/usr/local/go_workspace/src/github.com/skratchdot/open-golang/open
```
We're actually managing dependencies through the makefile on section `deps` you probably just need to append the new dependency [here](https://github.com/ernestio/ernest-cli/blob/develop/Makefile#L18) ;-)

**Comment by rawgni** [comment]
@adriacidre ah.. got it

**Comment by adriacidre** [comment]
In case the default system application does not exist (xdg-open on linux) the command does not print any output. 
```
$ ./ernest docs
$
```
Even is not possible accomplish this with open-golang library as they're not returning any error, would be nice to always print a default message like:
```
$ ./ernest docs
Visit ernest.io documentation site : http://ernest.io/documentation/
```
So in case nothing opens the url, the user at least, will have a handy link.
@rawgni do you think you can add this last bit to your pull request?

**Comment by rawgni** [comment]
@adriacidre yep

```
 ernest-cli git:(feat/156) ✗ ./ernest docs
Visit ernest.io documentation site : http://ernest.io/documentation/
```

**Comment by adriacidre** [comment]
cool, good job mate

**Pull request merged**
